# ステータス
TASK_STATUS_TODO = 10
TASK_STATUS_IN_PROGRESS = 20
TASK_STATUS_DONE = 30

# 優先度
TASK_PRIORITY_LOW = 1
TASK_PRIORITY_MEDIUM = 2
TASK_PRIORITY_HIGH = 3
TASK_PRIORITY_URGENT = 4

# ソート
SORT_ORDER_ASC = "asc"
SORT_ORDER_DESC = "desc"
DEFAULT_SORT_BY = "createdAt"
DEFAULT_SORT_ORDER = SORT_ORDER_DESC
